- name: "Provision user"
  block:
    - name: Adding user account {{ item }}
      user:
        name: "{{ item }}"
        shell: /bin/bash
        group: sudo

    - name: Pushing public key for {{ item }}
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'keys/{{ item }}.pub') }}"
        state: present

  rescue:
    - name: Error provisioning {{ item }}
      debug:
        msg: "Is there a public key in the 'keys' folder ({{ item }}.pub)?"